
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# ===============================
# DATABASE CONFIG
# ===============================

#spring.datasource.url=jdbc:mysql://localhost:3306/your_db_name
#spring.datasource.username=root
#spring.datasource.password=your_password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/saas-pos
spring.datasource.username=pos-user
spring.datasource.password=pos-password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



# Logging level
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

# Show SQL logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Custom log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n


springdoc.swagger-ui.path: /swagger
springdoc.api-docs.path: /api-docs